<?php

return [
    'version' => env('DMS_COMMAND_CATALOG_VERSION', 'v1'),

    'risk_by_intent' => [
        'reboot_device' => ['risk_level' => 'medium', 'requires_approval' => false, 'rollback_command' => ''],
        'run_command_device' => ['risk_level' => 'medium', 'requires_approval' => false, 'rollback_command' => ''],
        'uninstall_agent_device' => ['risk_level' => 'high', 'requires_approval' => true, 'rollback_command' => 'reinstall_agent'],
        'create_policy' => ['risk_level' => 'medium', 'requires_approval' => false, 'rollback_command' => 'remove_policy'],
        'apply_policy' => ['risk_level' => 'medium', 'requires_approval' => false, 'rollback_command' => 'remove_policy_assignment'],
        'get_device_status' => ['risk_level' => 'low', 'requires_approval' => false, 'rollback_command' => ''],
        'project_inventory' => ['risk_level' => 'low', 'requires_approval' => false, 'rollback_command' => ''],
        'unknown' => ['risk_level' => 'low', 'requires_approval' => false, 'rollback_command' => ''],
    ],

    'high_risk_patterns' => [
        '/\bnetsh\s+advfirewall\s+set\s+allprofiles\s+state\s+off\b/i',
        '/\bset-mppreference\b.*\bdisablerealtimemonitoring\b/i',
        '/\bsc\s+stop\s+(?:windefend|mpssvc)\b/i',
        '/\bshutdown\.exe\s+\/s\b/i',
        '/\brundll32\.exe\s+user32\.dll,lockworkstation\b/i',
        '/\bnew-localuser\b|\bnet\s+user\b.*\s+\/add\b/i',
    ],

    'run_command_templates' => [
        [
            'slug' => 'restart_print_spooler',
            'phrases' => ['restart print service', 'print service', 'spooler'],
            'script' => 'powershell -NoProfile -ExecutionPolicy Bypass -Command "Restart-Service -Name Spooler -Force"',
            'run_as' => 'system',
            'timeout_seconds' => 240,
            'confidence' => 0.84,
            'rationale' => 'Mapped print-service restart request to spooler restart command.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'clear_temp_files',
            'phrases' => ['clear temp files', 'clear temp', 'clean temp', 'temporary files'],
            'script' => 'powershell -NoProfile -ExecutionPolicy Bypass -Command "$paths=@($env:TEMP,\'C:\\Windows\\Temp\'); foreach($p in $paths){ if(Test-Path $p){ Get-ChildItem -Path $p -Force -ErrorAction SilentlyContinue | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue }}"',
            'run_as' => 'system',
            'timeout_seconds' => 420,
            'confidence' => 0.80,
            'rationale' => 'Mapped temp-cleanup request to PowerShell cleanup command.',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'collect_diagnostic_snapshot',
            'phrases' => ['run diagnostic', 'diagnostic', 'health scan', 'security scan'],
            'script' => 'powershell -NoProfile -ExecutionPolicy Bypass -Command "Get-ComputerInfo | ConvertTo-Json -Depth 4 -Compress"',
            'run_as' => 'system',
            'timeout_seconds' => 360,
            'confidence' => 0.78,
            'rationale' => 'Mapped diagnostic request to system information snapshot.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'shutdown_device',
            'phrases' => ['shut down', 'shutdown device', 'power off'],
            'script' => 'shutdown.exe /s /t 0 /f /c "Control plane requested shutdown"',
            'run_as' => 'system',
            'timeout_seconds' => 180,
            'confidence' => 0.82,
            'rationale' => 'Mapped shutdown request to endpoint shutdown command.',
            'risk_level' => 'high',
            'requires_approval' => true,
            'rollback_command' => 'reboot_device',
        ],
        [
            'slug' => 'install_chrome',
            'phrases' => ['install chrome', 'deploy chrome'],
            'script' => 'winget install --id Google.Chrome --silent --accept-source-agreements --accept-package-agreements',
            'run_as' => 'system',
            'timeout_seconds' => 900,
            'confidence' => 0.76,
            'rationale' => 'Mapped Chrome install request to winget install command.',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'rollback_command' => 'uninstall_software',
        ],
        [
            'slug' => 'update_all_software',
            'phrases' => ['update all outdated application', 'update all outdated applications', 'upgrade all applications', 'update all devices', 'update devices in'],
            'script' => 'winget upgrade --all --silent --accept-source-agreements --accept-package-agreements',
            'run_as' => 'system',
            'timeout_seconds' => 1200,
            'confidence' => 0.74,
            'rationale' => 'Mapped software update request to winget upgrade command.',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'disable_firewall',
            'phrases' => ['disable firewall', 'turn off firewall', 'firewall off'],
            'script' => 'netsh advfirewall set allprofiles state off',
            'run_as' => 'system',
            'timeout_seconds' => 240,
            'confidence' => 0.83,
            'rationale' => 'Mapped firewall disable request to netsh command.',
            'risk_level' => 'high',
            'requires_approval' => true,
            'rollback_command' => 'enable_firewall',
        ],
        [
            'slug' => 'enable_firewall',
            'phrases' => ['enable firewall', 'turn on firewall', 'firewall on'],
            'script' => 'netsh advfirewall set allprofiles state on',
            'run_as' => 'system',
            'timeout_seconds' => 240,
            'confidence' => 0.82,
            'rationale' => 'Mapped firewall enable request to netsh command.',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'rollback_command' => 'disable_firewall',
        ],
        [
            'slug' => 'restart_agent',
            'phrases' => ['restart agent', 'restart dms agent', 'restart endpoint management service', 'reinstall agent', 'reinstall the agent', 're-install agent'],
            'script' => 'powershell -NoProfile -ExecutionPolicy Bypass -Command "Restart-Service -Name DmsAgent -Force"',
            'run_as' => 'system',
            'timeout_seconds' => 300,
            'confidence' => 0.74,
            'rationale' => 'Mapped agent restart request to service restart command.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'check_windows_updates',
            'phrases' => ['check windows updates', 'scan update status', 'check for updates'],
            'script' => 'powershell -NoProfile -ExecutionPolicy Bypass -Command "UsoClient StartScan"',
            'run_as' => 'system',
            'timeout_seconds' => 900,
            'confidence' => 0.72,
            'rationale' => 'Mapped update-check request to Windows update scan.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'install_windows_updates',
            'phrases' => ['install windows updates', 'apply windows updates', 'install critical updates'],
            'script' => 'powershell -NoProfile -ExecutionPolicy Bypass -Command "UsoClient StartInstall"',
            'run_as' => 'system',
            'timeout_seconds' => 3600,
            'confidence' => 0.70,
            'rationale' => 'Mapped Windows update install request to update installer trigger.',
            'risk_level' => 'medium',
            'requires_approval' => true,
            'rollback_command' => '',
        ],
        [
            'slug' => 'ping_test',
            'phrases' => ['ping test', 'test connectivity', 'check network connectivity'],
            'script' => 'cmd.exe /c "ping -n 4 8.8.8.8"',
            'run_as' => 'default',
            'timeout_seconds' => 120,
            'confidence' => 0.70,
            'rationale' => 'Mapped connectivity request to ping test.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'dns_test',
            'phrases' => ['dns test', 'check dns', 'resolve hostname'],
            'script' => 'cmd.exe /c "nslookup example.com"',
            'run_as' => 'default',
            'timeout_seconds' => 120,
            'confidence' => 0.70,
            'rationale' => 'Mapped DNS check request to nslookup.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
        [
            'slug' => 'get_network_info',
            'phrases' => ['network info', 'network details', 'ip settings'],
            'script' => 'cmd.exe /c "ipconfig /all"',
            'run_as' => 'default',
            'timeout_seconds' => 180,
            'confidence' => 0.74,
            'rationale' => 'Mapped network information request to ipconfig.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
    ],

    'policy_suggestions' => [
        [
            'slug' => 'disable_usb_policy',
            'phrases' => ['disable usb', 'block usb', 'disbale usb', 'disble usb', 'diable usb', 'usb disbale', 'usb disble'],
            'command' => 'reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\RemovableStorageDevices" /v Deny_All /t REG_DWORD /d 1 /f',
            'run_as' => 'system',
            'timeout_seconds' => 300,
            'confidence' => 0.82,
            'rationale' => 'Detected USB disable/block requirement.',
            'risk_level' => 'medium',
            'requires_approval' => true,
            'rollback_command' => 'enable_usb',
        ],
        [
            'slug' => 'enable_usb_policy',
            'phrases' => ['enable usb', 'allow usb', 'enble usb', 'usb enble'],
            'command' => 'reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\RemovableStorageDevices" /v Deny_All /t REG_DWORD /d 0 /f',
            'run_as' => 'system',
            'timeout_seconds' => 300,
            'confidence' => 0.80,
            'rationale' => 'Detected USB allow/enable requirement.',
            'risk_level' => 'medium',
            'requires_approval' => false,
            'rollback_command' => 'disable_usb',
        ],
        [
            'slug' => 'gpupdate_force_policy',
            'phrases' => ['gpupdate'],
            'command' => 'gpupdate /force',
            'run_as' => 'system',
            'timeout_seconds' => 300,
            'confidence' => 0.78,
            'rationale' => 'Detected GPUpdate policy command requirement.',
            'risk_level' => 'low',
            'requires_approval' => false,
            'rollback_command' => '',
        ],
    ],
];
