[program:dms-queue]
process_name=%(program_name)s
directory=/var/www/dms/current/backend
command=/usr/bin/php artisan queue:work redis --queue=horizon,default --sleep=1 --tries=3 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/dms/shared/storage/logs/queue-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=3600
