[program:dms-scheduler]
process_name=%(program_name)s
directory=/var/www/dms/current/backend
command=/usr/bin/php artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/dms/shared/storage/logs/scheduler.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=10
stopwaitsecs=3600
